# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.10
yarn_mappings=1.21.10+build.3
loader_version=0.18.1
loom_version=1.13-SNAPSHOT

# Mod Properties
mod_name=MarTweaks
mod_id=martweaks
mod_version=1.0.4
mod_authors=uhmbyee / Mariany Pinkston
mod_description=Miscellaneous tweaks and modifications to fit vanilla gameplay.
mod_page_url=https://www.curseforge.com/minecraft/mc-mods/martweaks
mod_git_url=https://github.com/marianyp/MarTweaks
mod_license=ARR

maven_group=dev.mariany.martweaks
archives_base_name=martweaks

# Dependencies
fabric_version=0.138.3+1.21.10
modmenu_version=16.0.0-rc.1
owo_version=0.12.24+1.21.9